apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy-1
spec:
  replicas: 5
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: mycont-1
        image: shaikmustafa/paytm:movie
        ports:
        - containerPort: 80